//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPSD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeachingToolsEntities : DbContext
    {
        public TeachingToolsEntities()
            : base("name=TeachingToolsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonAssignment> PersonAssignments { get; set; }
        public virtual DbSet<PersonDiscipline> PersonDisciplines { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Standard> Standards { get; set; }
    }
}
