//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPSD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDiscipline
    {
        public int PersonID { get; set; }
        public int DisciplinaryID { get; set; }
        public Nullable<System.DateTime> DisciplinaryDate { get; set; }
        public string DisciplinaryDescription { get; set; }
        public string ParentNotified { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Person Person { get; set; }
    }
}
